import type { Metadata } from "next";
import { roboto } from "../styles/fonts"
import "../styles/globals.scss";

export const metadata: Metadata = {
  title: "Sii Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <main className="main-container">{children}</main>
      </body>
    </html>
  );
}
